### ISSUE TITLE
How about having examples in Anagha's article?

### ISSUE THREAD

**Issue by WriteMugdha** [UdaanSTC/GutsAndGlory#10]
Love the words and the flip cards. Can we make those flip cards more appealing by including images in them along with examples. For example, a picture of one person offering another a basket of apples, and the person accepting the gift says, "I accept all these apples except for this one."

It's easier to remember the pictures, and that's why the examples. What say? Doable?

PS: Am I logging this issue properly? I am not necessarily tying it with the right html file. Is that okay?

**Comment by AninditaBasu** [comment]
Perfectly okay. We all know which article you are referring to: [http://udaanstc.github.io/GutsAndGlory/html/anagha.html](http://udaanstc.github.io/GutsAndGlory/html/anagha.html)

Also, great idea. Let me get one example up. I'll try making a cartoon through [http://www.makebeliefscomix.com/](http://www.makebeliefscomix.com/).

**Comment by AninditaBasu** [comment]
@WriteMugdha 
See the article now and let me know if this is what you wanted: [http://udaanstc.github.io/GutsAndGlory/html/anagha.html](http://udaanstc.github.io/GutsAndGlory/html/anagha.html)

Only the first word-pair has a cartoon as of now. I used [https://www.bitstrips.com/pageone/](https://www.bitstrips.com/pageone/).

**Comment by WriteMugdha** [comment]
That's just so quick and cool! :)

This will be more effective. Isn't it? Worth taking efforts?

**Comment by AninditaBasu** [comment]
My only concern is whether we can find a cartoonable sentence for each word-pair. Want to take a shot at that?

**Comment by thomasnibu** [comment]
Checking to see if a reply by email works :)

This is nice! Yeah, getting a single sentence for all examples might be a challenge. Maybe we can ask our contributors for ideas?

Nibu

-----Original Message-----

**Comment by AninditaBasu** [comment]
Yep, reply though emails work :-)
Good idea, that, about asking our contributors. If they could be directed to this issue...

**Comment by WriteMugdha** [comment]
Please edit these sentences.. am not thinking twice. Just pouring thoughts here.
-  When exposed to sun, UV radiation may affect our skin. However, we must also remember that loss of vitamin D is an effect of not enjoying sun rays. (A simple visual of a wrinkled face in sun, and a sad face without sun with "Vit D" crossed out).
-  Assenting with everyone is not going to ensure an ascent in corporate life. (A picture of a butt-kissing employee with his boss?)
-  I received a great compliment from the boss when I designed complementary benefits for all employees within the budget she had allocated. (Happy employee with an appreciative boss in the think cloud?)
-  I doubt if he is prepared to take more questions. (Two students in a class conversing looking at the tired lecturer.)
-  It's fun to see a butterfly flipping its colorful wings.
-  My login credentials always fail the first time I try to log in.
-  This beautiful lace flower on the skirt is coming loose. I'm worried I might lose it if I don't fix it today.
-  Our school principal was a man of principles.

More tomorrow. Got to wrap up the day. Was dedicated to two orgs - STC and the other one. Now some family time.

Talk to you guys tomorrow.

**Comment by AninditaBasu** [comment]
okay, so, quite a few done. Still pending
- affect - effect
- discreet - discrete
- precede - proceed
- deploy - install
- adaptive - responsive
- migrate - upgrade

**Comment by alka-acharya** [comment]
I loved the idea of the cartoons with example of the confused words. It's a Hit! 
For revert, should we also add the point that never use "revert back" because revert means "to go back"? It's a common mistake.
A last point: Have we decided a limit on how many confused words are we going to cover here? Or are we planning to add more?

**Comment by AninditaBasu** [comment]
Good point about "revert back".
And no, we weren't planning to add any more pairs...unless you have any in mind?

**Comment by alka-acharya** [comment]
@AninditaBasu - I did have a few more pairs. But, on second thoughts, I think the existing list is good! Thank you.

For example of "revert back" - I have seen many HR and consultants use it in their emails. An example (True life incident :) -
Hi we have a very Urgent requirement for the position of a Portal Developer
Looking for Immediate Joiners or candidate with Notice period of Less than 1 Month kindly revert back to me with your most updated resumes if interested
