### ISSUE TITLE
Edits to Shivi's article

### ISSUE THREAD

**Issue by AninditaBasu** [UdaanSTC/GutsAndGlory#12]
@sisivasu
Hi Shivi,

Your article is up for review at [http://udaanstc.github.io/GutsAndGlory/html/shivi.html](http://udaanstc.github.io/GutsAndGlory/html/shivi.html). You'll notice I made two major changes to your article:
- I left out your "acknowledgements" text completely. Reason: you've already acknowledged those people at the beginning of the article. Doing so again at the end would be slightly embarrassing for them, I am sure :)
- I did not use the James Bertrand quote (“Once we rid ourselves of traditional thinking, we can get on with creating the future." - James Bertrand") Even though the quote is present all over the internet, I could find no person called James Bertrand - nothing about who, what, where etc. so I thought it best that we do not add to the internet copy-paste clutter.

Let me know if you disagree with either edit. Also let me know if you don't like any of the other small edits.

Also, one item is pending from your side: a tweetable sentence (about 110 characters or so) that captures the essence of your article, and that we can use in teasers and to auto-populate Twitter popup boxes. Do write in the tweetable.

**Comment by sisivasu** [comment]
No objections! Would you consider adding the following quote in stead of the Bertrand's one, if you think it is worth it? "We can't change anything until we get some fresh ideas, until we begin to see things differently". - James Hillman

Does this sound OK for the tweetable?: "The key to becoming a successful innovator is all in your mindset!"

**Comment by AninditaBasu** [comment]
added the new quote.

tweetable, it's perfectly okay but it's not wow! let's sleep over it.

**Comment by sisivasu** [comment]
Here is another shot at the tweetable:

"Being innovative doesn’t always necessarily mean making history. Start with a small idea! Here's how: <link to the article>"

**Comment by sisivasu** [comment]
A couple more:
- What does it take to turn yourself into an innovator? Read <> to find out.
- Learn to think like an innovator. Some easy tips to get you started are here: <>

**Comment by AninditaBasu** [comment]
How about: Tips to start thinking like an innovator. Small ideas, big returns. ...URL...

**Comment by sisivasu** [comment]
Sounds good! Let's finalize this, then? Or you want me to try further?

**Comment by AninditaBasu** [comment]
Let's finalise this. If you have a better idea before 30 Sep, let me know.

**Comment by sisivasu** [comment]
OK! I will. Thanks.
