### ISSUE TITLE
Wrap text around flip boards?

### ISSUE THREAD

**Issue by sisivasu** [UdaanSTC/GutsAndGlory#13]
Hi @AninditaBasu - I loved the way you've used the flipping animation in the article! A few concerns, though: 
- The text boxes appear a little too big for the font size used in the article. Should we consider minimizing them a bit [possible at all?]?
- The placement of the boxes might have a slight impact on the reader's experience [they seem to interrupt the flow]. Could something like "Wrap text around" kinda thing be done, if it is not too much of an effort?

I can help you implement these changes, if you agree, too!

Thanks,
- Shivi

**Comment by AninditaBasu** [comment]
@sisivasu 
Hi Shivi,
My thoughts:
- The flip boxes are of two sizes: (i) large, which you see in Anagha's article, and (ii) normal, which you see in your article, in the home page, and a few more places. Only these two sizes are used, for a consistent look and feel. The size has been set to accommodate both the front and the back text. If the size of the box in your article is reduced, the text at the back (biography) cannot be accommodated, plus, for the home page, the contributor's profile (at the front) cannot be accommodated.
- Readers don't read; they scan. Only writers read and only editors read. White space in an article is a signal to the reader that the text can be consumed (scanned) in bite-sized pieces. The boxes break the flow to give the readers some breathing space.

Those were my thoughts but I'll defer to the majority, so tagging @thomasnibu and @writemugdha.

**Comment by thomasnibu** [comment]
Yes, that's something I observed too. But then I realized it's because of the content on the other side of the flip card. 
Maybe we can centralize the text horizontally and vertically, so that the white space is balanced on all sides?

Warm Regards,

Nibu

**Comment by sisivasu** [comment]
A suggestion, hoping that it would help reduce the size of the boxes - 
Why do we need so much of text on the other side of the card? Can't it just be a hyperlink to, say a relevant Wiki page?

**Comment by AninditaBasu** [comment]
Several reasons:
- The box size is the same on other pages as well. I am not in favour of having different-sized boxes for articles.
- There is no relevant Wikipedia page. The quotes aren't always present on Wikipedia.
- Why do you want to send people away from your page and towards Wikipedia?

**Comment by sisivasu** [comment]
Okie, point#1 is reason enough to discard my suggestion! :(

**Comment by AninditaBasu** [comment]
@sisivasu 
Would you want me to remove the flip effect altogether? That would mean the box is only as big as the quote text.
So, what do you think: is the short bio of the person being quoted really needed (if yes, "flip" remains) or no.

**Comment by sisivasu** [comment]
@AninditaBasu

I used those quotes in my original copy just as a way of beefing the content up - I'm not too sure if any reader would be interested in the short bio of the people quoted.

If we were to retain the flip effect with 'something else' on the other side of the card, what could that be? If there are no other options [which I believe is the case], then [sorry, I hate to say this] I'm for removing the flip effect completely. And, if we decide to go with that plan, instead of putting the quotes within boxes, why don't we insert them right at the end of the paragraphs, as in the original?

**Comment by thomasnibu** [comment]
I think the flip effect reduces scroll to some extent. Also gives the user something to do. 
Same reason why people buy manual cars as opposed to automatics : )

Nibu

**Comment by sisivasu** [comment]
@thomasnibu: "I think the flip effect reduces scroll to some extent."

Sorry, not sure I get this - how? By facilitating short breaks?

**Comment by thomasnibu** [comment]
You have content on both sides of the card, right. So if it were not flipping, the content that is behind (or in front) will need to be placed below the existing image. I was thinking it would add to the length of the page..? Unless you reduce the size of the image and place the text on the side...
But irrespective of the scroll, I'd retain it simply for the interactive effect. (I hope I've used the right one here :D

Nibu

**Comment by sisivasu** [comment]
Hmm - okie, but the question now is whether or not the content that's on the back side should be retained. :)

**Comment by AninditaBasu** [comment]
I think the content on the back can be removed.

I made the changes and checked in the file. @sisivasu please review the file; if it looks okay, please close this issue.

**Comment by sisivasu** [comment]
I like this version a lot better! Thanks much.

Now that there are no boxes in the article, should we remove this tip that's shown at the top: "Move your cursor over the white boxes that you see in this article; some more text will be revealed." ?

**Comment by AninditaBasu** [comment]
Aargh! How did I miss that one?
Corrected and committed.
