### ISSUE TITLE
Patents article - suggestions

### ISSUE THREAD

**Issue by thomasnibu** [UdaanSTC/GutsAndGlory#14]
It would be great if we could also look at a few examples of patents filed in the information area. Also, if the organization does not have an IPMS, what are the other options to privately file for a patent? What about costs? Are there private entities like we have investors who will fund you to file a patent? You could also provide the example of http://witworks.com/. They are an interesting Indian startup who help bring your idea to life. Of course, read the fine print : )

**Comment by AninditaBasu** [comment]
1. Shivi's article (mentioned as a related article at the end of this article) has two examples of techwriting-related patents. Do we need to reword the text in the Related section to draw attention to this fact?
2. If an organisation does not have IPMS... :-) i believe we're adding to Alka's misery; she'll have to research again. Let's draw her attention to this Issue.
3. What about costs: If the company is filing on your behalf, all costs are borne by the company and, not only that, you get an award too! What if you're filing all by yourself, as an individual? Point 2 would cover that.
4. Are there private entities: Let me research this a bit.

Am reading the witworks link now.
P.S.: By the time Udaan is released, I am sure all our authors will hate the very sight of us. I've already chewed Alka's brains out completely.

**Comment by AninditaBasu** [comment]
For point 2, I propose adding the following text at this location: "If your organisation does not have an IPMS, then contact your manager to find out how to proceed."

Instead, use this text: "If your organisation does not have an IPMS, look up the patent office of your country. In India, this office is at [http://ipindia.nic.in/](http://ipindia.nic.in/). As on the date of publishing this article, the fees for the e-filing of a patent by an individual is INR 1600."

What do you think @thomasnibu ?

Ref.: Fees info is here [http://ipindia.nic.in/ipr/patent/patent_FormsFees/Fees.pdf](http://ipindia.nic.in/ipr/patent/patent_FormsFees/Fees.pdf).

**Comment by thomasnibu** [comment]
super!

Maybe we can get some people who have filed patent requests to respond on linkedin?

Nibu

-----Original Message-----

**Comment by thomasnibu** [comment]
Which brings me to the next question. When would you want to file a patent request with the Indian authorities and when would you file one in the US. What are the implications. I hope I'm not digressing too much, but I think this is important. There might be many of us who have ideas and work for smaller organizations. The ease of the other option (of filing it as an individual) might just bring some people out. Because, when someone has a bright idea, he/she does not want to reveal it if the WIIFM is not addressed. And since it is not addressed, it gathers dust, till an Udaan can rekindle that spark again. Or so I'm hoping.

Nibu

-----Original Message-----

**Comment by AninditaBasu** [comment]
Adding @alka-thanvi to the discussion.
Hello Alka, do let me know what additions, deletions, modifications you'd like to make to the article.

**Comment by AninditaBasu** [comment]
Adding @alka-acharya to the discussion.
Hello Alka, do let me know what additions, deletions, modifications you'd like to make to the article.

**Comment by AninditaBasu** [comment]
@alka-acharya,
The images in the article are all updated now.

**Comment by alka-acharya** [comment]
Thanks for updating the images, Anindita  - @AninditaBasu . 
Thanks for your comments and questions, Nibu @thomasnibu n Anindita. I am working on them.

**Comment by SamarthaVashishtha** [comment]
Interesting discussion! I'm trying to address some questions in this comment.

_When would you want to file a patent request with the Indian authorities and when would you file one in the US?_

As I mentioned in the article, patents are "jurisdictional" in nature. That implies that a patent filed in the US would normally not be enforceable through the Indian judicial system. Similarly, a patent filed in India will not safeguard the filing entity's commercial interests in the US.

Therefore, one files a patent in the country where one anticipates filing it would be most profitable. If a company's primary customer base is in the US, it will file a US patent. Else, India. Ideally, both or an international patent.

For individuals trying to safeguard inventions they aren't yet making money from, it'd be cost effective to file an Indian patent. 

_If an organisation does not have IPMS...?_

...then the budding inventor should talk to the organization's legal department and understand the filing process.

_Are there private entities like we have investors who will fund you to file a patent?_

Possibly; if you can answer their WIIFM concerns. If one wants to start a company based on a unique idea, filing a patent could give one that elusive competitive advantage. So, patent filing costs could be built into the seed funding or angel investment pitches.

@thomasnibu @AninditaBasu @alka-acharya

**Comment by SamarthaVashishtha** [comment]
Some more unsolicited thoughts, this time about the following request:

_It would be great if we could also look at a few examples of patents filed in the information area._

I am not entirely sure adding such examples would add to the value of the article. Let me explain why. 

The purpose of patenting and this article is to help authors get comfortable with the concept and process of patenting; to help them see "possibilities". Patenting essentially requires that writers step beyond their traditional roles in the organization and connect with their company's primary business. So, restricting their outlook to ideas just related to "information" might define an unreasonable comfort zone. In fact, filing information-related patents is possible only in a handful of organizations, such as IBM and possibly Adobe.

So, writers should groom themselves as domain experts and file patents around whatever their organization's core business is. That will ensure sustainable ideation and patenting success.

Just my inconsequential two cents!

@AninditaBasu @alka-acharya @thomasnibu

**Comment by thomasnibu** [comment]
I see what you are saying. But here's a different school of thought. 
Like they say, charity begins at home. So also innovation. To a good extent. As a writer I'd try to relate to this article if it showed me the possibilities in my area. And also keep in mind that there's a common thread connecting Udaan's varied audience. By starting in a familiar area, I'm not restricting the writer, but merely suggesting a place to start. And examples add the 'I-could-have-thought-of-it-too' factor. Because otherwise, the sky is the limit. Needless to say, domains we work in are very different. So innovation examples that we already can see, specific to technology, might make little sense to someone who doesn't understand it, and is thus not really appreciated by those who don't work in that particular area. Which kind of brings us back to square one.

**Comment by alka-acharya** [comment]
Very sorry for my delayed respose. Thank you for your patience. 

## Tried to address the questions/comments:

Regarding adding examples to the article: My vote: Avoid examples in this article.
I understand Nibu's point as to how some examples can help. I did gather a couple of UI related patents: 
https://www.google.co.in/patents/US5072412 
https://www.google.co.in/patents/US20050054381
https://www.google.co.in/patents/USD608366
But, I agree with Samartha about why we should avoid examples specific to Tech comm. 

Also, another thought: Not sure how to choose the examples to be included in the article - I mean on what basis can I choose an example or two to be included in the article - Would it offend anyone or any organisation for being left out? We do have a couple of examples in Jana's interview. 

## Request your thoughts. 

To address the points "If IPMS does not exist" & "About filing through private entities", I suggest the following updates:
In section "Submit the invention internally":
Change line: If your organisation does not have an IPMS, then contact your manager to find out how to proceed.
TO
If your organisation does not have an IPMS, then contact your manager to find out how to proceed or you can approach your organisation's legal team to understand the filing process. 

## If you are not working for an organisation or your organisation is not going to pursue your invention, then you can try to sell your invention or idea to prospective private investors who can bear the cost of patent filing. 

Other changes (section-wise):
What is a patent?
In a corporate set up --> In a corporate setup

An inventor's journey - From invention to patent

## In the diagram, the last box says "Inventer". We should change it to "Inventor"

@SamarthaVashishtha ; @thomasnibu ; @AninditaBasu.

**Comment by alka-acharya** [comment]
Please ignore the formatting issues (The bold + big font text) in my earlier post. Not sure how to correct it. :( I tried a couple of ways.

**Comment by AninditaBasu** [comment]
@alka-acharya 

I incorporated comments as under:
- In Submit the invention internally, I changed the text to: "If your organisation does not have an IPMS, contact either your manager or your legal department to find out how to proceed. If you are not working for an organisation or your organisation will not file your invention, try selling your idea to private or angel investors (but read the fine print carefully before signing up)."
- Corrected "in a corporate set up"
- Corrected the spelling mistake in the diagram.

I don't see why picking and choosing patent examples will offend any organisation or person. However, to address your concerns, I am giving the examples very little visibility by pushing them right to the end of the article. :wink:

Don't worry about the odd formatting in your comments. :laughing: 

Please review the changes. If things look okay, do close this issue.

**Comment by alka-acharya** [comment]
@AninditaBasu - Thank you so much for incorporating the comments. The examples at the end look good. :) Thank you! I am closing this issue. Fixes #14

**Comment by alka-acharya** [comment]
@AninditaBasu - I did some R&D to see how to close issues. Tried using Pull requests - but did not see the Close pull request button. Hence, tried using the keyword "Fixes #14 . 
Hope this works.

**Comment by AninditaBasu** [comment]
:smile: All you need to do is scroll down this page and click the "Close" button.

**Comment by thomasnibu** [comment]
Received the following comments regarding the Patent article. Please review

"The article is very clear, detailed, and is an easy read for beginners. However in my experience, the following details could also have been useful in the article.
·         Companies do market research to identify where the patented technology may be of use, where companies may need it. If the research suggests and if that geography’s financial market aligns with your revenue model, company can plan royalty models from interested clients in _that geography_. It means that we should not focus only on local geography, but identify other locations for the _need_ such as if the focus is on royalty model as well.

·         When users file a patent application at multiple locations, there is a concept of ‘Priority Date’. It applies to a set of specific countries under ‘Paris Conventions’. It helps when multiple companies are trying to address same problem and they know that only one can get the patent granted, for who files first. Since you cannot in general, file it at multiple countries at the same time, you file it in one geography and this date is your ‘Priority Date’. I am not too sure of another use case, but I think it is important to consider. "

**Comment by thomasnibu** [comment]
Added review comments from a fellow contributor. Or felli ;)

**Comment by alka-acharya** [comment]
Thanks for sharing the feedback and thanks to the fellow or felli contributor for reviewing the article. :)
For the first part of the feedback "Companies do market .... as well" - Both Samartha and I think that including it would be getting into a lot of detail, and hence, would not incorporate it.

For the second part of the feedback "When users file a patent .... important to consider", @AninditaBasu , request you to add the following statement under stage 6 "Await results"  at the end: 
Principle of 'Priority date': When you are seeking patent protection for the same invention in many countries, you do not have to file your application in those countries at the same time. As per "priority right", once you file a patent application in a country, you are entitled to claim priority for a period of twelve months and the filing date of your application is considered the “priority date" when you apply for protection in other countries. For more information, see https://en.wikipedia.org/wiki/Priority_right.

Thanks,
Alka

@SamarthaVashishtha ; @thomasnibu

**Comment by thomasnibu** [comment]
I've included the note as suggested below. Please check.

Warm Regards,

Nibu

-----Original Message-----

**Comment by alka-acharya** [comment]
Thank you, Nibu, @thomasnibu 

I want to request a change. I am sorry. 
Can we move the new content at the end of the earlier step - 5: File the patent.? You can copy-paste the below content there (I removed the part "Principle of 'Priority date':):

When you are seeking patent protection for the same invention in many countries, you do not have to file your application in those countries at the same time. As per "priority right", once you file a patent application in a country, you are entitled to claim priority for a period of twelve months and the filing date of your application is considered the “priority date" when you apply for protection in other countries. For more information, see https://en.wikipedia.org/wiki/Priority_right.

**Comment by thomasnibu** [comment]
Done. Please check.

Warm Regards,

Nibu

-----Original Message-----

**Comment by alka-acharya** [comment]
Checked the update. Looks good. Many thanks, Nibu - @thomasnibu .
Best regards,
Alka

**Comment by alka-acharya** [comment]
@AninditaBasu @thomasnibu  - Can we attach a snap of Jana to her interview? (Sorry if its too late - but the thought just occurred to me). I can ask her for one, if you think we can use it. Please let me know.

Thanks,
Alka

**Comment by AninditaBasu** [comment]
@alka-acharya Yes, good idea :smile: Can you get us the photo by 15 Nov? Also, a link to an online profile would be nice too.

**Comment by alka-acharya** [comment]
@AninditaBasu - Thank you! :) 

I have the photo (attached).

Linkedin profile link: https://www.linkedin.com/pub/jana-jenkins/12/407/a61

![janabluepages09](https://cloud.githubusercontent.com/assets/14192487/10969714/1b9bd63a-83f0-11e5-9633-f1e4b226f8fe.jpg)

**Comment by AninditaBasu** [comment]
updated the article. check? :smile:
