### ISSUE TITLE
Asha's article: battleship

### ISSUE THREAD

**Issue by AninditaBasu** [UdaanSTC/GutsAndGlory#15]
@thomasnibu 
1. Do we need a battleship image?
2. Do we need to educate people the WHY of  "no passengers on a battleship", maybe through an obscure popup?

**Comment by thomasnibu** [comment]
Let's look for a better free-to-use image. I agree that it does not add value. But I'm thinking that an all text article might also not be a good idea. Maybe a cartoon, for punctuation?
Yes, I think it might help. Again a cartoon maybe... All hands on deck... And someone says not me, I'm a just a passenger.... and they make him walk the plank.. or they make him a messenger... to the enemy.... I don't know... just rambling :D

Warm Regards,

Nibu

**Comment by AninditaBasu** [comment]
Let me try make a cartoon from one of these cartoon sites. This weekend, will do.

**Comment by AninditaBasu** [comment]
Could not make the cartoon. The cartoon resources on the web were inadequate.

I added a picture of a warship, and I think that explains the concept of "no passengers". @thomasnibu if you think the article looks okay with that pic, please close this issue.
