### ISSUE TITLE
Minor: Bio update

### ISSUE THREAD

**Issue by SamarthaVashishtha** [UdaanSTC/GutsAndGlory#19]
Hi,

  I couldn't figure out how to update my bio in the _gh-pages_ node. Could we update it to the following text?:

---

Samartha Vashishtha works as a Senior Content and Community Lead with Adobe Systems, where he’s primarily responsible for planning and delivering Help content for Photoshop, Lightroom, and Creative Cloud services. Samartha has previously spoken at international conferences on topics such as web communities, visual communication, and globalized content. 

Beyond work, Samartha is a published creative writer.

**Comment by AninditaBasu** [comment]
@SamarthaVashishtha 
Hi Samartha,
I updated the text. Could you please review, and if you need no further changes, close this Issue.

:smiley: You weren't able to update the page yourself because you don't have push access to this repository.

**Comment by SamarthaVashishtha** [comment]
The changes look good.
