### ISSUE TITLE
No TOC on Suyog's article

### ISSUE THREAD

**Issue by thomasnibu** [UdaanSTC/GutsAndGlory#20]
I can't see the TOC menu when I navigate to Suyog's article

**Comment by AninditaBasu** [comment]
:disappointed: A case of blind FindAll-ReplaceAll. I had accidentally introduced an error in the script tag that loads the conref-ed ToC. That one could be so stupid as to do a Replace All...

**Comment by AninditaBasu** [comment]
It's fixed now. Please review, and close this Issue if things look fine now.
