### ISSUE TITLE
Commonly confused words: some updates required.

### ISSUE THREAD

**Issue by AnaghaC** [UdaanSTC/GutsAndGlory#21]
The words accept and except are emphasized in this sentence. 

> To accept is to agree. The word except excludes something from a list.

Instead, can we emphasize the a in both accept and agree, and the exc in the except and exclude?
## 

In this sentence, can we emphasize the initials of affect, cause, and effect.
To affect a change is to cause it. And cause comes before effect, just like A and C
come before E.
## 

Migrate/upgrade: the explanation has an extra punctuation (") at the end.
On the panel on the back, do we need a period after Move Up? Does Up need a capital U?
## 

Some of the definitions are from OED/dictionary.com. Do we need to mention that?

**Comment by AninditaBasu** [comment]
All of @AnaghaC's comments incorporated.

**Comment by AninditaBasu** [comment]
Further comments received through peer review:

## 

The following points need corrected in Anagha’s write-up:
-  In the Twitter quote, she writes: “Can I ask you a question? You can but you may not. Avoid these vocab mistakes.” However, the “you can” contains an introduction. So, an introductory clause (or a comma) must be inserted before “but.” The corrected sentence in the Twitter quote should be: “You can, but you may not.” Also, I am unable to find sufficient references for using the shortened form of the word, but let us retain it.
-  The write-ups should be written as per the British English standards. Therefore, in the “adaptive – responsive” section, the word “customize” should be “customise.”
-  In the British English standards, the punctuation marks are placed OUTSIDE the quotation marks,
  unless they are a part of the quoted material. Also, some of the reference materials stress the use of single quotation marks in the British English. For quotations within quotations, the British English use double quotations. But, let us not be sticklers. I leave this point to the discretion of the writer. If she wishes, she can move the punctuation outside the quotation marks.

## 

These comments are incorporated as well. For the third comment, I vote we use single quotation marks for words or phrases we want to emphasise, and double quotation marks for conversations.

**Comment by AnaghaC** [comment]
I agree with the peer reviewer's comments about the punctuations inside/outside quotation marks. I don't agree with that particular style guideline in general, but until I write my own book on style, I should stick to something that the experts agree on. :)

Unrelated, but - Anindita, you have done more work than I have on this article. I vote we add your name as author.

**Comment by AninditaBasu** [comment]
Incorporated all comments.
:smile: I don't think we need to add my name as author. I only made the cartoons, so I mentioned my name in acknowledgements.

**Comment by AnaghaC** [comment]
More issues:

1) The definitions of respond/revert and adaptive/responsive have full stops. Do the other definitions need similar punctuations?

2) The conversation in the example for doubt/question has colons. In this case, do we need quotation marks?

**Comment by AninditaBasu** [comment]
1. They do.
2.  No, we don't.
   Looks okay now?

**Comment by AnaghaC** [comment]
I have one more request. If it's too late, please ignore.
- Affect = cause (verb). Effect = result (noun).
- Respond = reply. Revert = reset.
  Similarly, 
- Migrate = Move. Upgrade = Move up.
  Can we make the M in 'move' and 'move up' lower case?

Sorry about this. The more I look at a write-up (any write-up), the more likely I am to find yet another typo.

**Comment by thomasnibu** [comment]
Hi Anagha,

I think this information already exists. It's on the other side : ) http://udaanstc.github.io/GutsAndGlory/html/anagha.html

Warm Regards,

Nibu

-----Original Message-----

**Comment by AnaghaC** [comment]
Thanks, Nibu! I meant to point out that the third bullet point should have casing similar to the first two. :)

**Comment by thomasnibu** [comment]
Done. :)

Nibu

-----Original Message-----
