### ISSUE TITLE
Shivi Article Suggestions

### ISSUE THREAD

**Issue by thomasnibu** [UdaanSTC/GutsAndGlory#22]
1.  Quotes are good but I feel they are overused.
2.  The section Why Innovate At All does not quite fit the flow. Intro says that the article is for a person who wants to innovate. In that case, the person is convinced about why to innovate.
3.  How do you become a prolific innovator? Prolific does not seem to be the right word. Prolific means plentiful. So, prolific reader makes sense because that implies one reads a lot. Prolific innovater does not ring the bell. One is either an innovator or not one. Innovation is not measured in quantity.
4.  When ideas fail you, what can you do to keep yourself motivated? Needs more clarity on what this means. Do we want to say when your ideas fail?  Or do we want to say when you do not get an idea (ideas fail you would mean that).
5.  If you are the one who is seeking answers to these questions.... Change to if you are seeking answers to these questions…
6.  No human is perfect, nor so is a technical system or a piece of software. 'Delete so'.
7.  The more problematic the system is, the larger the scope for innovation there is. Delete 'there is'.
8.  Here are some of the reasons for your idea failing. Comment - reasons for failure of your idea?
9. And yes, and be bold and willing to face failures. Remove the second and... And yes, be bold...

**Comment by AninditaBasu** [comment]
-  Comment 1, @sisivasu, is it okay to delete the following quotes:
  -    Ideas won't keep. Something must be done about them.
  -    To have a great idea is to have lots of them.
  -    We can't change anything until we get some fresh ideas, until we begin to see things differently.
  -    If at first the idea is not absurd, then there will be no hope for it.
-  Comment 2. Retain the section. Reason, it still is nice to have an quick intro.
-  Comments 3, 5, 6, 7, 8, and 9 incorporated.
-  Comment 4. @sisivasu, I propose changing "When ideas fail you, what can you do to keep yourself motivated?" to "When you discover your idea wasn't so new after all, what can you do to keep yourself motivated". Okay to?

**Comment by sisivasu** [comment]
@AninditaBasu : Please go ahead and make the changes! Thank you.

**Comment by AninditaBasu** [comment]
Thanks, incorporated.
