### ISSUE TITLE
Feedback/Review of "Internalising a research mindset"

### ISSUE THREAD

**Issue by prajprad** [UdaanSTC/GutsAndGlory#23]
1.  The title of the article is very cryptic. I could not understand what it meant “Internalising”.
2.  The tweetable handle is also not really useful or does not give any idea about the topic.
3.  “I requested him to talk about various skills a technical communicator must have.” I would prefer “I requested him to talk about various skills that a technical communicator must have.”
4.  We should use “research mindset” with an article “a research mindset”.
5.  When I read through the cases, objectives, and methodology, I read through the boxes at the first go and skipped the information in between. It probably is a good idea to have it all in a table and provide the information that’s provided in between the line of boxes all at one go in a paragraph.
6.  “For example, some of the important attributes of a new tool will be price, learning curve, and compatibility with the existing system.” This seems out of the place. The cases are examples themselves.
7.  “The methodology varies from case to case.” This is completely redundant. It’s easily understood from the use cases.
8.  “Methodology” is such a jargon. Why can’t we just use “Analysis”? Or may be “Exploring”.
9.  “With clear measurables in hand, the next phase is collecting and analysing data.”  I think this is the “Methodology”? 
10.  “Any mistake at this stage can result in wrong conclusion, forcing the you to do it all over again.” Remove “the”.
11.  “To what extent good documentation saves support costs?” Suggest changing to “To what extent does good documentation save support costs?”
12.  “The scope of such topics cover the analysing statistical data of large samples to deduce quantitative results, which can also be supplemented with some insights from a qualitative research.” I totally didn’t understand this...just too many noun strings, long sentence, and overall too complex to understand the quantitative, qualitative part.
13.  “Some activities like user testing may...” If we are technical writers, we ought to follow our rules. Why are we using “like” here. We ought to use “such as”.
14.  “Data collection for big projects will be spread across a longer timeframe” “Time frame” Should be two words.
15.  “STC also undertakes...” paragraph comes in suddenly out of the blue. It needs to be placed after the next paragraph.

**Comment by AninditaBasu** [comment]
Incorporated comments #3, #4, #10, #11, #14
