### ISSUE TITLE
Some layout changes 

### ISSUE THREAD

**Issue by vinishgarg** [UdaanSTC/GutsAndGlory#5]
Here are a few comments for my entry at: http://udaanstc.github.io/GutsAndGlory/html/vinish.html.

[A] Headings: The writing style is conversational, as if I am speaking to live audience. While reading, I feel as if I am reading a small chapter from a story, a narrative, and so I do not feel the need for internal headings (Who stops you, Talk about your work). I want users to read it without a pause, without rest, as if they are also reading a sub plot from a story. 

And when we remove these two headings:
Let 'Who stops you' stay here as a new paragraph and combine it with the following paragraph that begins with 'If you are..". 
Likewise, let 'Talk about your work', stay here as a new paragraph and combine it with the following paragraph that begins with "Taxonomy. MadCap Flare. Acrolinx...."

[B] "LIke the smell of chlorine in bleach." Can you change it to "Like the smell of chlorine."

[B] "Or, a difference in opinion?" Can you move it to the next line, as if in a new paragraph?

[C] "That's it." Can you please make it in italics?

[D] "To hand out some pearls of wisdom if your mind...". Please rewrite to "Help yourself if your mind is still stuck at 'Who stops you':"

**Comment by AninditaBasu** [comment]
@vinishgarg 
I incorporated your comments. Page looks okay now?

**Comment by vinishgarg** [comment]
Thanks Anindita, Yes, it reads well now. However, I see some format issues now.
- "work.If you are excited.." We need space after the period.
- "Taxonomy. Madcap Flare. Acrolinx. CMS." Please start it as a new paragraph.

In Acknowledgements, please add another note:
The '...toothpaste left in the tube' is an unknown quote, source is not known.

---

Thanks again, Anindita.

**Comment by AninditaBasu** [comment]
Incorporated.
Thanks for your patience.

**Comment by vinishgarg** [comment]
Perfect. You can close it now. Thank you.
