### ISSUE TITLE
Status of articles

### ISSUE THREAD

**Issue by AninditaBasu** [UdaanSTC/GutsAndGlory#7]
A work item to track the status of the text part of the articles.

Podcasts for all articles is yet to be done.
# Emoji code

:bangbang: cause for concern
:sparkles: :star: :star2: ready for recording
:footprints: :soon: work-in-progress. no major concerns
# Status
1. Udaan home page. Work in progress. Not a major concern :footprints: :soon: 
2. Alka Acharya and Samartha Vashishtha: [You too can patent](http://udaanstc.github.io/GutsAndGlory/html/alka.html). Ready. :sparkles: :star: :star2: 
3. Anagha Chandratrey: [Commonly confused words](http://udaanstc.github.io/GutsAndGlory/html/anagha.html). Ready. :sparkles: :star: :star2: Reviewed, edits incorporated.
4. Anindita Basu: [Of managers and manuals](http://udaanstc.github.io/GutsAndGlory/html/anindita.html). Ready. :sparkles: :star: :star2: Reviewed, edits incorporated.
5. Asha Mokashi: [No passengers on the battleship](http://udaanstc.github.io/GutsAndGlory/html/asha.html). Ready. :sparkles: :star: :star2: Reviewed, edits incorporated.
6. Basreena Basheer: [It's a L10N thing](http://udaanstc.github.io/GutsAndGlory/html/basreena.html). Ready. :sparkles: :star: :star2: Reviewed, edits incorporated.
7. Meghashri Dalvi: [Internalising a research mindset](http://udaanstc.github.io/GutsAndGlory/html/meghashri.html). Ready. :sparkles: :star: :star2: Reviewed, edits incorporated.
8. Rohit Nair: [A day in the life of a technical editor](http://udaanstc.github.io/GutsAndGlory/html/rohit.html).  Ready. :sparkles: :star: :star2: Reviewed, edits incorporated.
9. Prajakta Pradhan: [Who is the user](http://udaanstc.github.io/GutsAndGlory/html/prajakta.html) Ready. :sparkles: :star: :star2: 
10. Sheece Baghdadi: [To be or not to be](http://udaanstc.github.io/GutsAndGlory/html/sheece.html) Ready. :sparkles: :star: :star2:  
11. Shivi Sivasubramanian: [Awaken the innovator in you](http://udaanstc.github.io/GutsAndGlory/html/shivi.html). Ready. :sparkles: :star: :star2: Reviewed, edits incorporated.
12. Surbhi Chattkara: [Management lessons that children teach us](http://udaanstc.github.io/GutsAndGlory/html/surbhi.html) Ready. :sparkles: :star: :star2:
13. Suyog Ketkar: Information design. Ready. :sparkles: :star: :star2: 
14. Vinish Garg: [Be your own story](http://udaanstc.github.io/GutsAndGlory/html/vinish.html). Ready :sparkles: :star: :star2: Reviewed.
15. [Quiz](http://udaanstc.github.io/GutsAndGlory/html/quiz.html)  Ready. :sparkles: :star: :star2:
16. Conference team.  Work in progress. :footprints: :soon: 
17. Contest winners.  Work in progress. Not a major concern :footprints: :soon: 
18. Admin council. No one has told them anything yet. :footprints: :soon:

**Comment by AninditaBasu** [comment]
@thomasnibu @WriteMugdha @sheeceB
Peoples, mitron, fellow sufferers, 
Do you have any further updates on the articles? (See the first comment in this Issue.) Sep 15 has come and gone. Let's **not** accept any articles after Sep 25.

**Comment by AninditaBasu** [comment]
@thomasnibu
10 articles + 1 play is ready. Time to tell the authors to start voice-recording them?

**Comment by thomasnibu** [comment]
I was thinking we give a week's time to critic each other's article. Since no one is volunteering, we assign articles and request each author to look at one other article and bury it like it was written by an enemy ;) Feedback can be sent to us and we don't reveal who has edited the article.
We can then ask them to record. What say?

Warm Regards,  

```
Nibu
```

-----Original Message-----

**Comment by AninditaBasu** [comment]
And, if they don't respond within a week, we freeze the doc anyway, right?
Also, you are an optimist.

**Comment by WriteMugdha** [comment]
I agree. Sounds too optimistic. We need to freeze the articles now, and get
into recording.
