### ISSUE TITLE
Status of podcasts

### ISSUE THREAD

**Issue by AninditaBasu** [UdaanSTC/GutsAndGlory#8]
A work item to track the article podcasts.

The status is updated to incorporate comments to this Issue.
1.  Alka Acharya and Samartha Vashishtha: [You too can patent](http://udaanstc.github.io/GutsAndGlory/html/alka.html#audio)  Ready. :sparkles: :star: :star2:
2.  Anagha Chandratrey: [Commonly confused words](http://udaanstc.github.io/GutsAndGlory/html/anagha.html#audio)  Ready. :sparkles: :star: :star2:
3.  Anindita Basu: [Of managers and manuals](http://udaanstc.github.io/GutsAndGlory/html/anindita.html#audio)  Ready. :sparkles: :star: :star2:
4.  Asha Mokashi: [No passengers on the battleship](http://udaanstc.github.io/GutsAndGlory/html/asha.html#audio)  Ready. :sparkles: :star: :star2:
5.  Basreena Basheer: [It's a L10N thing](http://udaanstc.github.io/GutsAndGlory/html/basreena.html#audio)  Ready. :sparkles: :star: :star2:
6.  Meghashri Dalvi: [Internalising a research mindset](http://udaanstc.github.io/GutsAndGlory/html/meghashri.html#audio)  Ready. :sparkles: :star: :star2:
7.  Prajakta Pradhan: [Who is the user](http://udaanstc.github.io/GutsAndGlory/html/prajakta.html#audio)  Ready. :sparkles: :star: :star2:
8.  Rajib Borkataki: [Ascend, naturally](http://udaanstc.github.io/GutsAndGlory/html/rajib.html#audio)  Ready. :sparkles: :star: :star2:
9.  Rohit Nair: Editing. [A day in the life of a technical editor](http://udaanstc.github.io/GutsAndGlory/html/rohit.html#audio)  Ready. :sparkles: :star: :star2:
10.  Sheece Baghdadi: [To be or not to be](http://udaanstc.github.io/GutsAndGlory/html/sheece.html#audio) Ready. :sparkles: :star: :star2:
11.  Shivi Sivasubramanian: [Awaken the innovator in you](http://udaanstc.github.io/GutsAndGlory/html/shivi.html#audio)  Ready. :sparkles: :star: :star2:
12.  Surbhi Chattkara: [Management lessons that children teach us](http://udaanstc.github.io/GutsAndGlory/html/surbhi.html#audio)  Ready. :sparkles: :star: :star2:
13.  Suyog Ketkar: [This side up](http://udaanstc.github.io/GutsAndGlory/html/suyog.html#audio)  Ready. :sparkles: :star: :star2:
14.  Vinish Garg: [Be your own story](http://udaanstc.github.io/GutsAndGlory/html/alka.html#audio)  Ready. :sparkles: :star: :star2:

**Comment by AninditaBasu** [comment]
@thomasnibu 
Can you please check these once? If the download okay, if they play right, ...

**Comment by thomasnibu** [comment]
Playing ok.... Did random sampling. Especially the one's I haven't heard.

**Comment by AninditaBasu** [comment]
closing, then.
